config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  namespace :user do
    get :clock_in
    get :clock_out
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_event.rb
class ClockEvent < ApplicationRecord
  belongs_to :user
  validate :check_clock_in_event, on: :create
  validate :check_clock_out_event, on: :update


  private

  def check_clock_in_event
    errors.add(:clock_in, 'exists') if user.clock_events.where(stop_at: nil).present?
  end

  def check_clock_out_event
    errors.add(:clock_in, 'does not exist') if user.clock_events.where(stop_at: nil).blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clock_events

  def clocked_status
    clock_events.where(stop_at: nil).blank? ? 'Clocked Out' : 'Clocked In'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @clock_events = current_user.clock_events.order(start_at: :desc)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def clock_in
    clock_event = ClockEvent.create(start_at: Time.zone.now, user_id: current_user.id)

    flash[:error] = clock_event.errors.full_messages.to_sentence if clock_event.errors.present?
    redirect_to root_path
  end

  def clock_out
    clock_event = current_user.clock_events.order(start_at: :desc).first
    clock_event.update(stop_at: Time.zone.now)

    flash[:error] = clock_event.errors.full_messages.to_sentence if clock_event.errors.present?
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def period(clock_event)
    stop_at = clock_event.stop_at ? clock_event.stop_at : Time.zone.now
    diff = stop_at - clock_event.start_at
    hours = (diff / 1.hour).round
    minutes = ((diff / 1.minutes) - hours * 60).round

    "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}"
  end
end

app/views/home/_clock_events_tab.html.erb
<div class="ui tab" data-tab="clock_events">
  <table class="ui celled table">
    <thead>
    <tr>
      <th>Clock in</th>
      <th>Clock out</th>
      <th>Period</th>
    </tr>
    </thead>
    <tbody>
    <% @clock_events.each do |clock_event| %>
      <tr>
        <td data-label="Clock in"><%= clock_event.start_at %></td>
        <td data-label="Clock out"><%= clock_event.stop_at %></td>
        <td data-label="Period"><%= period(clock_event) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/home/_general_tab.html.erb
<div class="ui tab active" data-tab="general">
  <% unless flash[:error].nil? && flash[:alert].nil? %>
    <div class="ui error message">
      <%= content_tag :div, 'Errors', class: 'header' %>
      <% flash.each do |name, msg| %>
        <%= content_tag :p, msg %>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <a class="ui teal image label">
      <%= current_user.email %>
      <div class="detail"><%= current_user.clocked_status %></div>
    </a>
  </div>
  <div class="ui hidden divider"></div>
  <div class="ui actions">
    <%= link_to 'Clock In', user_clock_in_path, class: "ui button left green" %>
    <%= link_to 'Clock Out', user_clock_out_path, class: "ui button right red" %>
    <%= link_to destroy_user_session_path, method: :delete, class: "ui button right labeled icon" do%>
      <i class="right arrow icon"></i>
      Sign out
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% content_for(:header) { 'Home' } %>

<div class="ui top attached tabular menu">
  <a class="active item" data-tab="general">
    General
  </a>
  <a class="item" data-tab="clock_events">
    Clock events
  </a>
</div>
<div class="ui bottom attached segment">
  <%= render partial: 'general_tab' %>
  <%= render partial: 'clock_events_tab' %>
</div>
<script>
  $(document).ready(function () {
    $('.tabular.menu .item').tab();
  });
</script>

app/views/layouts/_errors.html.erb
<% unless flash[:error].nil? && flash[:alert].nil? %>
  <div class="ui error message">
    <%= content_tag :div, 'Errors', class: 'header' %>
    <% flash.each do |_name, msg| %>
      <%= content_tag :p, msg %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeClocker</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="content">
  <h2 class="ui header left"><%= yield(:header)%></h2>
  <%= yield %>
</div>
</body>
</html>